web/myblog/blog/urls.py
from django.conf.urls import url
from . import views
app_name = 'blog'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(),name="index"),
    url(r'^article/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesView.as_view(), name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    url(r'^tag/(?P<pk>[0-9]+)/$', views.tag, name='tag')
]

web/myblog/blogproject/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'', include('comments.urls')),
    url(r'^search/', include('haystack.urls')),
]

web/myblog/blog/models.py
import markdown
from django.utils.html import strip_tags
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
# Create your models here.
class Category(models.Model):
	name = models.CharField(max_length=100,verbose_name='文章类型')
	def __str__(self):
		return self.name
	class Meta:
		verbose_name = "文章类型"
		verbose_name_plural = '文章类型'

class Tag(models.Model):
	name = models.CharField(max_length=100,verbose_name='文章标签')
	def __str__(self):
		return self.name
	class Meta:
		verbose_name = "文章标签"
		verbose_name_plural = '文章标签'

class Article(models.Model): #文章属性
	title = models.CharField(max_length=70,verbose_name='标题')
	body = models.TextField(verbose_name='正文')
	created_time = models.DateTimeField(verbose_name='创建时间')
	modified_time = models.DateTimeField(verbose_name='修改时间')
	abstract = models.CharField(max_length=200,blank=True,verbose_name='文章摘要')
	category = models.ForeignKey(Category,verbose_name='文章类型')
	tags = models.ManyToManyField(Tag,blank=True,verbose_name='文章标签')
	author = models.ForeignKey(User,verbose_name='文章作者')
	views = models.PositiveIntegerField(default=0)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('blog:detail',kwargs={'pk':self.pk})

	def increase_views(self):
		self.views += 1
		self.save(update_fields=['views'])

	def save(self, *args, **kwargs):
		if not self.abstract:

			md = markdown.Markdown(extensions=[
				'markdown.extensions.extra',
				'markdown.extensions.codehilite',
			])
			self.abstract = strip_tags(md.convert(self.body))[:100]
		super(Article, self).save(*args, **kwargs)

	class Meta:
		ordering = ['-created_time']
		verbose_name = "文章"
		verbose_name_plural = '文章'

web/myblog/templates/base.html
<!doctype html>
{% load staticfiles %}
{% load blog_tags %}
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="description" content="">
  <meta name="keywords" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <title>个人博客</title>
  <meta name="renderer" content="webkit">
  <meta http-equiv="Cache-Control" content="no-siteapp"/>
  <link rel="icon" type="image/png" href="{% static '/blog/i/favicon.png' %}">
  <meta name="mobile-web-app-capable" content="yes">
  <link rel="icon" sizes="192x192" href="{% static '/blog/i/app-icon72x72@2x.png' %}">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="Amaze UI"/>
  <link rel="apple-touch-icon-precomposed" href="{% static '/blog/i/app-icon72x72@2x.png' %}">
  <meta name="msapplication-TileImage" content="{% static '/blog/i/app-icon72x72@2x.png' %}">
  <meta name="msapplication-TileColor" content="#0e90d2">
  <link rel="stylesheet" href="{% static '/blog/css/amazeui.min.css' %}">
  <link rel="stylesheet" href="{% static '/blog/css/app.css' %}">
    <title>Black &amp; White</title>
    <style>
        span.highlighted {
            color: red;
        }
    </style>
</head>
<header class="am-topbar am-topbar-inverse">
  <!--<h1 class="am-topbar-brand">-->
    <!--<a href="{% url 'blog:index' %}">MAYBACH</a>-->
  <!--</h1>-->

  <button class="am-topbar-btn am-topbar-toggle am-btn am-btn-sm am-btn-success am-show-sm-only" data-am-collapse="{target: '#doc-topbar-collapse'}"><span class="am-sr-only">导航切换</span> <span class="am-icon-bars"></span></button>

  <div class="am-collapse am-topbar-collapse" id="doc-topbar-collapse">
    <ul class="am-nav am-nav-pills am-topbar-nav">
      <li class="am-active"><a href="{% url 'blog:index' %}">首页</a></li>
      <li class="am-dropdown" data-am-dropdown>
        <a class="am-dropdown-toggle" data-am-dropdown-toggle href="javascript:;">
          分类<span class="am-icon-caret-down"></span>
        </a>
        <ul class="am-dropdown-content">
            {% get_category as get_category_list %}
		    {% for category in get_category_list %}
            <li><a href="{% url 'blog:category' category.pk %}">{{ category }}</a></li>
            {% empty %}
                暂无分类！
            {% endfor %}
        </ul>
      </li>

        <li class="am-dropdown" data-am-dropdown>
        <a class="am-dropdown-toggle" data-am-dropdown-toggle href="javascript:;">
          归档<span class="am-icon-caret-down"></span>
        </a>
        <ul class="am-dropdown-content">
        {% archives as date_list %}
        {% for date in date_list %}
        <li>
            <a href="{% url 'blog:archives' date.year date.month %}">{{date.year}} 年 {{date.month}} 月</a>
        </li>
        {% empty %}
            暂无归档！
        {% endfor %}
        </ul>
      </li>
    </ul>


    <form class="am-topbar-form am-topbar-right am-form-inline" role="search" action="{% url 'haystack_search' %}">
      <div class="am-form-group">
        <input type="text" class="am-form-field am-input-sm"  name="q" placeholder="搜索" required>
          <button type="submit" class="am-btn am-btn-primary">搜索</button>

      </div>
    </form>
  </div>
</header>
<body id="blog">





<!-- content srart -->
<div class="am-g am-g-fixed blog-fixed">
    {% block main %}
    {% endblock main %}

    <div class="am-u-md-4 am-u-sm-12 blog-sidebar">
        <div class="blog-sidebar-widget blog-bor">
            <h2 class="blog-text-center blog-title"><span>关于我</span></h2>
            <img src="{% static '/blog/i/maybach.jpg' %}" alt="about me" class="blog-entry-img" >

                        <p>MAYBACH</p>
            <a href="https://github.com/maybachv5"><span class="am-icon-github am-icon-fw blog-icon"></span></a>

            <a href="https://weibo.com/u/1766302390/home?wvr=5"><span class="am-icon-weibo am-icon-fw blog-icon"></span></a>
      <p>You're Closer Than You Think!</p>

        </div>

        <div class="blog-clear-margin blog-sidebar-widget blog-bor am-g ">
            <h2 class="blog-title"><span>标签云</span></h2>
            <div class="am-u-sm-12 blog-clear-padding">{% get_tags as tag_list %}
			{% for tag in tag_list %}
            <a href="{% url 'blog:tag' tag.pk %}" class="blog-tag">{{tag}}({{tag.article_set.count}})</a>
            {% empty %}
				暂无标签！
			{% endfor %}
            </div>
        </div>


    </div>

</div>
<!-- content end -->


 <footer class="blog-footer">

    <div class="blog-text-center">© 2017 MAYBACH</div>
  </footer>



<!--[if (gte IE 9)|!(IE)]><!-->
<script src="{% static '/blog/js/jquery.min.js' %}"></script>
<!--<![endif]-->
<!--[if lte IE 8 ]>
<script src="http://libs.baidu.com/jquery/1.11.3/jquery.min.js"></script>
<script src="http://cdn.staticfile.org/modernizr/2.8.3/modernizr.js"></script>
<script src="assets/js/amazeui.ie8polyfill.min.js"></script>
<![endif]-->
<script src="{% static '/blog/js/amazeui.min.js' %}"></script>
<!-- <script src="assets/js/app.js"></script> -->
</body>
</html>