web/myblog/blog/urls.py
from django.conf.urls import url
from . import views
app_name = 'blog'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(),name="index"),
    url(r'^article/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesView.as_view(), name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    url(r'^tag/(?P<pk>[0-9]+)/$', views.tag, name='tag')
]

web/myblog/blogproject/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'', include('comments.urls')),
    url(r'^search/', include('haystack.urls')),
]

web/myblog/comments/urls.py
from django.conf.urls import url
from . import views

app_name = 'comments'
urlpatterns = [
	url(r'^comment/article/(?P<article_pk>[0-9]+)/$',views.article_comment,name='article_comment'),
]

web/myblog/blog/models.py
import markdown
from django.utils.html import strip_tags
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
# Create your models here.
class Category(models.Model):
	name = models.CharField(max_length=100,verbose_name='文章类型')
	def __str__(self):
		return self.name
	class Meta:
		verbose_name = "文章类型"
		verbose_name_plural = '文章类型'

class Tag(models.Model):
	name = models.CharField(max_length=100,verbose_name='文章标签')
	def __str__(self):
		return self.name
	class Meta:
		verbose_name = "文章标签"
		verbose_name_plural = '文章标签'

class Article(models.Model): #文章属性
	title = models.CharField(max_length=70,verbose_name='标题')
	body = models.TextField(verbose_name='正文')
	created_time = models.DateTimeField(verbose_name='创建时间')
	modified_time = models.DateTimeField(verbose_name='修改时间')
	abstract = models.CharField(max_length=200,blank=True,verbose_name='文章摘要')
	category = models.ForeignKey(Category,verbose_name='文章类型')
	tags = models.ManyToManyField(Tag,blank=True,verbose_name='文章标签')
	author = models.ForeignKey(User,verbose_name='文章作者')
	views = models.PositiveIntegerField(default=0)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('blog:detail',kwargs={'pk':self.pk})

	def increase_views(self):
		self.views += 1
		self.save(update_fields=['views'])

	def save(self, *args, **kwargs):
		if not self.abstract:

			md = markdown.Markdown(extensions=[
				'markdown.extensions.extra',
				'markdown.extensions.codehilite',
			])
			self.abstract = strip_tags(md.convert(self.body))[:100]
		super(Article, self).save(*args, **kwargs)

	class Meta:
		ordering = ['-created_time']
		verbose_name = "文章"
		verbose_name_plural = '文章'

web/myblog/comments/models.py
from django.db import models
# Create your models here.

class Comment(models.Model):
	name = models.CharField(max_length=100)
	email = models.EmailField(max_length=255)
	text = models.TextField()
	create_time = models.DateTimeField(auto_now_add=True)
	article = models.ForeignKey('blog.Article')
	def __str__(self):
		return self.text[:20]

web/myblog/blog/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse
from .models import Article,Category,Tag
from comments.forms import CommentForm
from django.views.generic import ListView
import markdown
from django.db.models import Q
# Create your views here.
# def index(request):
# 	article_list = Article.objects.all()
# 	return  render(request,'blog/index.html',context={'article_list':article_list})

# def category(request,pk):
# 	cate = get_object_or_404(Category, pk=pk)
# 	article_list = Article.objects.filter(category=cate)
# 	return render(request, 'blog/index.html', context={'article_list': article_list})

# def archives(request,year,month):
# 	article_list = Article.objects.filter(created_time__year=year,created_time__month=month)
# 	return render(request, 'blog/index.html', context={'article_list': article_list})

class IndexView(ListView):
    model = Article
    template_name = 'blog/index.html'
    context_object_name = 'article_list'
    paginate_by = 3

    def get_context_data(self, **kwargs):
        """
        在视图函数中将模板变量传递给模板是通过给 render 函数的 context 参数传递一个字典实现的，
        例如 render(request, 'blog/index.html', context={'post_list': post_list})，
        这里传递了一个 {'post_list': post_list} 字典给模板。
        在类视图中，这个需要传递的模板变量字典是通过 get_context_data 获得的，
        所以我们复写该方法，以便我们能够自己再插入一些我们自定义的模板变量进去。
        """

        # 首先获得父类生成的传递给模板的字典。
        context = super().get_context_data(**kwargs)

        # 父类生成的字典中已有 paginator、page_obj、is_paginated 这三个模板变量，
        # paginator 是 Paginator 的一个实例，
        # page_obj 是 Page 的一个实例，
        # is_paginated 是一个布尔变量，用于指示是否已分页。
        # 例如如果规定每页 10 个数据，而本身只有 5 个数据，其实就用不着分页，此时 is_paginated=False。
        # 关于什么是 Paginator，Page 类在 Django Pagination 简单分页：http://zmrenwu.com/post/34/ 中已有详细说明。
        # 由于 context 是一个字典，所以调用 get 方法从中取出某个键对应的值。
        paginator = context.get('paginator')
        page = context.get('page_obj')
        is_paginated = context.get('is_paginated')

        # 调用自己写的 pagination_data 方法获得显示分页导航条需要的数据，见下方。
        pagination_data = self.pagination_data(paginator, page, is_paginated)

        # 将分页导航条的模板变量更新到 context 中，注意 pagination_data 方法返回的也是一个字典。
        context.update(pagination_data)

        # 将更新后的 context 返回，以便 ListView 使用这个字典中的模板变量去渲染模板。
        # 注意此时 context 字典中已有了显示分页导航条所需的数据。
        return context

    def pagination_data(self, paginator, page, is_paginated):
        if not is_paginated:
            # 如果没有分页，则无需显示分页导航条，不用任何分页导航条的数据，因此返回一个空的字典
            return {}

        # 当前页左边连续的页码号，初始值为空
        left = []

        # 当前页右边连续的页码号，初始值为空
        right = []

        # 标示第 1 页页码后是否需要显示省略号
        left_has_more = False

        # 标示最后一页页码前是否需要显示省略号
        right_has_more = False

        # 标示是否需要显示第 1 页的页码号。
        # 因为如果当前页左边的连续页码号中已经含有第 1 页的页码号，此时就无需再显示第 1 页的页码号，
        # 其它情况下第一页的页码是始终需要显示的。
        # 初始值为 False
        first = False

        # 标示是否需要显示最后一页的页码号。
        # 需要此指示变量的理由和上面相同。
        last = False

        # 获得用户当前请求的页码号
        page_number = page.number

        # 获得分页后的总页数
        total_pages = paginator.num_pages

        # 获得整个分页页码列表，比如分了四页，那么就是 [1, 2, 3, 4]
        page_range = paginator.page_range

        if page_number == 1:
            # 如果用户请求的是第一页的数据，那么当前页左边的不需要数据，因此 left=[]（已默认为空）。
            # 此时只要获取当前页右边的连续页码号，
            # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 right = [2, 3]。
            # 注意这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
            right = page_range[page_number:page_number + 2]

            # 如果最右边的页码号比最后一页的页码号减去 1 还要小，
            # 说明最右边的页码号和最后一页的页码号之间还有其它页码，因此需要显示省略号，通过 right_has_more 来指示。
            if right[-1] < total_pages - 1:
                right_has_more = True

            # 如果最右边的页码号比最后一页的页码号小，说明当前页右边的连续页码号中不包含最后一页的页码
            # 所以需要显示最后一页的页码号，通过 last 来指示
            if right[-1] < total_pages:
                last = True

        elif page_number == total_pages:
            # 如果用户请求的是最后一页的数据，那么当前页右边就不需要数据，因此 right=[]（已默认为空），
            # 此时只要获取当前页左边的连续页码号。
            # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 left = [2, 3]
            # 这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]

            # 如果最左边的页码号比第 2 页页码号还大，
            # 说明最左边的页码号和第 1 页的页码号之间还有其它页码，因此需要显示省略号，通过 left_has_more 来指示。
            if left[0] > 2:
                left_has_more = True

            # 如果最左边的页码号比第 1 页的页码号大，说明当前页左边的连续页码号中不包含第一页的页码，
            # 所以需要显示第一页的页码号，通过 first 来指示
            if left[0] > 1:
                first = True
        else:
            # 用户请求的既不是最后一页，也不是第 1 页，则需要获取当前页左右两边的连续页码号，
            # 这里只获取了当前页码前后连续两个页码，你可以更改这个数字以获取更多页码。
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
            right = page_range[page_number:page_number + 2]

            # 是否需要显示最后一页和最后一页前的省略号
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True

            # 是否需要显示第 1 页和第 1 页后的省略号
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True

        data = {
            'left': left,
            'right': right,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'first': first,
            'last': last,
        }

        return data

def detail(request, pk):
    article = get_object_or_404(Article,pk=pk)
    article.increase_views()
    article.body = markdown.markdown(article.body,
    extensions=['markdown.extensions.extra','markdown.extensions.codehilite', 'markdown.extensions.toc',])
    form  = CommentForm()
    comment_list = article.comment_set.all()
    context = {'article': article,
               'form': form,
               'comment_list': comment_list
    }
    return render(request, 'blog/detail.html', context=context)





def tag(request,pk):
	ta = get_object_or_404(Tag,pk=pk)
	article_list = Article.objects.filter(tags=ta)
	return render(request, 'blog/index.html', context={'article_list': article_list})

class CategoryView(IndexView):
    def get_queryset(self):
        cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        return super(CategoryView, self).get_queryset().filter(category=cate)

        # def category(request,pk):
        # 	cate = get_object_or_404(Category, pk=pk)
        # 	article_list = Article.objects.filter(category=cate)
        # 	return render(request, 'blog/index.html', context={'article_list': article_list})

        # def archives(request,year,month):
        # 	article_list = Article.objects.filter(created_time__year=year,created_time__month=month)
        # 	return render(request, 'blog/index.html', context={'article_list': article_list})
class ArchivesView(IndexView):
    def get_queryset(self):
        year=self.kwargs.get('year')
        month=self.kwargs.get('month')
        return super(ArchivesView, self).get_queryset().filter(created_time__year=year,created_time__month=month)



def search(request):
    q = request.GET.get('q')
    error_msg = ''

    if not q:
        error_msg = "请输入关键词"
        return render(request, 'blog/index.html', {'error_msg': error_msg})

    article_list = Article.objects.filter(Q(title__icontains=q) | Q(body__icontains=q))
    return render(request, 'blog/index.html', {'error_msg': error_msg,
                                               'article_list': article_list})

web/myblog/templates/blog/detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load blog_tags %}
{% block main %}
<div class="am-u-md-8 am-u-sm-12">
      <article class="am-article blog-article-p">
        <div class="am-article-hd">
          <h1 class="am-article-title blog-text-center">{{article.title}}</h1>
          <p class="am-article-meta blog-text-center">
                <span class="am-icon-archive" title="分类"> &nbsp;</span><span><a> {{article.category}}</a></span> &nbsp;</a></span>
				<span class="am-icon-user" title="作者"> &nbsp;</span><span><a> {{article.author}}</a></span> &nbsp;</a></span>
				<span class="am-icon-calendar" title="时间"> &nbsp;</span><span><a>{{article.created_time.year}}/{{article.created_time.month}}/{{article.created_time.day}}</a></span> &nbsp;</a></span>
                <span class="am-icon-eye" title="阅读量"> &nbsp;</span><span><a>{{ article.views }}</a></span> &nbsp;</a></span>
                <span class="am-icon-comments" title="评论数"> &nbsp;</span><span><a>{{ article.comment_set.count }}</a></span> &nbsp;</a></span>
          </p>
        </div>
        <div class="am-article-bd">
         <p>{{article.body|safe}}</p>
        </div>
      </article>

        <div class="am-g blog-article-widget blog-article-margin">
          <div class="am-u-lg-4 am-u-md-5 am-u-sm-7 am-u-sm-centered blog-text-center">
            <span class="am-icon-tags"> &nbsp;</span>
             {% for tag in article.tags.all %}
            <a href="{% url 'blog:tag' tag.pk %}">{{tag.name}}</a>
             {% empty %}
                暂无标签！
             {% endfor %}
            <hr>
          </div>
        </div>

        <!--<hr>-->
        <!--<div class="am-g blog-author blog-article-margin">-->
          <!--{% for comment in comment_list %}-->
          <!--<div class="am-u-sm-3 am-u-md-3 am-u-lg-2">-->
            <!--<img src="{% static '/blog/i/f15.jpg' %}" alt="" class="blog-author-img am-circle">-->
          <!--</div>-->
          <!--<div class="am-u-sm-9 am-u-md-9 am-u-lg-10">-->
          <!--<h3><span>评论信息：</span><span class="blog-color">{{ comment.name }}({{ comment.create_time }})</span></h3>-->
            <!--<p>{{comment.text}}</p>-->
          <!--</div>-->
          <!--{% empty %}-->
		    <!--暂无评论！-->
  	  <!--{% endfor %}-->
        <!--</div>-->
        <!--<hr>-->
     {% for comment in comment_list %}
        <hr>
        <div class="am-g blog-author blog-article-margin">
          <div class="am-u-sm-3 am-u-md-3 am-u-lg-2">
            <img src="{% static '/blog/i/f15.jpg' %}" alt="" class="blog-author-img am-circle">
          </div>
          <div class="am-u-sm-9 am-u-md-9 am-u-lg-10">
          <h3><span>评论信息： &nbsp;&nbsp;</span><span class="blog-color">{{ comment.name }}({{ comment.create_time }})</span></h3>
            <p>{{comment.text}}</p>
          </div>

        </div>

        <hr>
        {% empty %}
		    暂无评论！
        {% endfor %}
        <!--<ul class="am-pagination blog-article-margin">-->
          <!--<li class="am-pagination-prev"><a href="#" class="">&laquo; 一切的回顾</a></li>-->
          <!--<li class="am-pagination-next"><a href="">不远的未来 &raquo;</a></li>-->
        <!--</ul>-->

        <hr>

        <form class="am-form am-g" id="comment-form" name="comment-form" action="{% url 'comments:article_comment' article.pk %}" method="POST">
          {% csrf_token %}
            <h3 class="blog-comment">评论</h3>
          <fieldset>
            <div class="am-form-group am-u-sm-4 blog-clear-left">
				 {{ form.name }}
				 {{ form.name.errors }}
            </div>
            <div class="am-form-group am-u-sm-4">
                 {{form.email}}
				 {{ form.email.errors }}
            </div>
            <div class="am-form-group">
                    {{form.text}}
					{{form.text.errors}}
            </div>
            <p><button type="submit" class="am-btn am-btn-default">发表评论</button></p>
          </fieldset>

        </form>

        <hr>
    </div>
{% endblock main %}

web/myblog/templates/blog/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load blog_tags %}
{% block main %}
    <div class="am-u-md-8 am-u-sm-12">
			  {% for article in article_list %}
        <article class="am-g blog-entry-article">

            <div class=" blog-entry-text">
                <h1><a href="{{article.get_absolute_url}}">{{article.title}}</a></h1>
                <span class="am-icon-archive " style="font-size:8px" title="分类"> &nbsp;</span ><span style="font-size:8px"><a> {{article.category}}</a></span> &nbsp;</a></span>
				<span class="am-icon-user" style="font-size:8px" title="作者"> &nbsp;</span><span style="font-size:8px"><a> {{article.author}}</a></span> &nbsp;</a></span>
				<span class="am-icon-calendar" style="font-size:8px" title="时间"> &nbsp;</span><span style="font-size:8px"><a>{{article.created_time.year}}/{{article.created_time.month}}/{{article.created_time.day}}</a></span> &nbsp;</a></span>
                <span class="am-icon-eye" style="font-size:8px" title="阅读量"> &nbsp;</span><span style="font-size:8px"><a>{{ article.views }}</a></span> &nbsp;</a></span>
                <span class="am-icon-comments" style="font-size:8px" title="评论数"> &nbsp;</span><span style="font-size:8px"><a>{{ article.comment_set.count }}</a></span> &nbsp;</a></span>
                <p>{{article.abstract}}</p>
                <a href="{{ article.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav"></span></a>

            </div>
        </article>
        {% empty %}
            <div class="no-post">暂时还没有发布的文章！</div>
        {% endfor %}
        <ul class="am-pagination am-pagination-centered">
          {% if is_paginated %}
          {% if first %}
            <li><a href="?page=1">1</a></li>
          {% endif %}
          {% if left %}
            {% if left_has_more %}
                <span>...</span>
            {% endif %}
            {% for i in left %}
                <li><a href="?page={{ i }}">{{ i }}</a></li>
            {% endfor %}
          {% endif %}
            <li class="am-active"><a href="?page={{ page_obj.number }}">{{ page_obj.number }}</a></li>
          {% if right %}
            {% for i in right %}
                <li><a href="?page={{ i }}">{{ i }}</a></li>
            {% endfor %}
            {% if right_has_more %}
              <span>...</span>
            {% endif %}
          {% endif %}
          {% if last %}
            <li><a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a></li>
          {% endif %}
          {% endif %}
        </ul>
    </div>
{% endblock main %}